version: '3.6'

services:
  ### PHP-FPM ##############################################
  php-fpm:
    expose:
      - "9000"
    restart: always
    build:
      context: .docker/php
      dockerfile: Dockerfile
      target: dev
      args:
        USER_ID: ${DOCKER_USER_UID}
        USER_NAME: ${DOCKER_USER_NAME}
        GROUP_ID: ${DOCKER_GROUP_ID}
    user: ${DOCKER_USER_NAME}
    environment:
      - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
    extra_hosts:
      - host.docker.internal:${DOCKER_HOST_IP}
    depends_on:
      - mysql
      - maildev
    networks:
      - bridge
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      - ./.docker/php/php.ini:/usr/local/etc/php/php.ini

  ### phpMyAdmin ###########################################
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql:db
    ports:
      - "8090:80"
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - mysql
    networks:
      - bridge

  ### MAILDEV ###############################################
  maildev:
    build: .docker/maildev
    ports:
      - "8085:80"
    networks:
      - bridge