version: '3.6'

services:
  ### NGINX Server #########################################
  http:
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      # App shares
      - ${APP_SHARED_PATH_HOST}/.env:/var/www/.env
      - ${APP_SHARED_PATH_HOST}/web/images:/var/www/web/images
      - ${APP_SHARED_PATH_HOST}/web/upload:/var/www/web/upload
      - ${APP_SHARED_PATH_HOST}/app/config/parameters.yml:/var/www/app/config/parameters.yml
      - ${APP_SHARED_PATH_HOST}/app/logs:/var/www/app/logs
      - ${APP_SHARED_PATH_HOST}/var/uploads:/var/www/var/uploads
      - ${APP_SHARED_PATH_HOST}/web/images:/var/www/web/images

  ### PHP-FPM ##############################################
  php-fpm:
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      - ./.docker/php/php.ini:/usr/local/etc/php/php.ini
      # App shares
      - ${APP_SHARED_PATH_HOST}/.env:/var/www/.env
      - ${APP_SHARED_PATH_HOST}/web/images:/var/www/web/images
      - ${APP_SHARED_PATH_HOST}/web/upload:/var/www/web/upload
      - ${APP_SHARED_PATH_HOST}/app/config/parameters.yml:/var/www/app/config/parameters.yml
      - ${APP_SHARED_PATH_HOST}/app/logs:/var/www/app/logs
      - ${APP_SHARED_PATH_HOST}/app/uploads:/var/www/var/uploads
      - ${APP_SHARED_PATH_HOST}/web/images:/var/www/web/images

  ### MailDev ##############################################
  maildev:
    build: ./maildev
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bezbahilru_maildev.rule=Host(`mail.bezbahil.aw-dev.ru`)"
      - "traefik.docker.network=traefik_traefik"
      - "traefik.http.services.bezbahilru_maildev_webapp.loadbalancer.server.port=80"
    networks:
      - backend
      - traefik

networks:
  traefik_default:
    external: true
  bridge:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.226.0/28