# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
  always_authenticate_before_granting: true
  encoders:
    AppBundle\Entity\User\User:
      algorithm: bcrypt
  providers:
    gpn_user_provider:
      id: gpn.user_provider
    fos_userbundle:
      id: fos_user.user_provider.username_email

  firewalls:
    # disables authentication for assets and the profiler, adapt it according to your needs
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    api:
      pattern:   ^/api
      stateless: true
      security: true
      anonymous: true
      lexik_jwt:
        authorization_header:
          enabled: true
          prefix: Bearer
          name: Authorization
        cookie:
          enabled: false
          name: BEARER
        query_parameter:
          enabled: false
          name: bearer
        throw_exceptions: false
        create_entry_point: true
        authentication_provider: lexik_jwt_authentication.security.authentication.provider
        authentication_listener: lexik_jwt_authentication.security.authentication.listener

    admin:
      context: admin
      pattern: ^/admin
      security: true
      form_login:
        login_path: fos_user_security_login
        check_path: fos_user_security_check
        provider: fos_userbundle
        csrf_token_generator: security.csrf.token_manager
        # if you are using Symfony < 2.8, use the following config instead:
        # csrf_provider: form.csrf_provider

      logout:
        path: fos_user_security_logout
        target: index
      anonymous: true

    gpn:
      pattern: ^/
      context: gpn
      security: true
      # activate different ways to authenticate
      provider: gpn_user_provider
      gpn_generic:
        cas_server_url: "%gpn_cas_server_url%"

      anonymous: ~
      # activate different ways to authenticate

      # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
      #http_basic: ~

      # https://symfony.com/doc/current/security/form_login_setup.html
      #form_login: ~
  access_control:
    - { path: ^/api/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/api/api_login, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/api, role: ROLE_USER }
    - { path: ^/admin/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/login_check, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/fakeServer, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/admin.*$, role: ROLE_ADMIN }
    - { path: ^/.*$, role: ROLE_USER }

  role_hierarchy:
    ROLE_ADMIN: [ROLE_USER]