# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value
    logs_directory: '%kernel.root_dir%/logs'
    cache_directory: '%kernel.root_dir%/cache'
    uploads_directory: '%kernel.root_dir%/../web/uploads'
    users_directory: '%kernel.root_dir%/../web/uploads/users'
    tags_directory: '%kernel.root_dir%/../web/uploads/tags'
    themes_directory: '%kernel.root_dir%/../web/uploads/themes'

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    app.admin.user:
        class: AppBundle\Admin\User\UserAdmin
        arguments: [ ~, 'AppBundle\Entity\User\User', ~ ]
        tags:
            - { name: sonata.admin, group: 'users', manager_type: orm, label: 'Пользователи' }